**Pandas – Quick Start Guide**

The `pandas` library provides high-performance, easy-to-use data structures and data analysis tools. The main data structure is the `DataFrame`, which we can think of as an in-memory 2D table (like a spreadsheet, with column names and row labels). Many features available in Excel are available programmatically, such as creating pivot tables, computing columns based on other columns, plotting graphs, etc. We can also group rows by column value, or join tables much like in SQL. Pandas is also great at handling time series.

This tutorial explains some difference and key features with spreadsheet programs like Excel, Google Sheets, LibreOffice Calc, Apple Numbers and other Excel-compatible spreadsheet software. In this tutorial we will go through the main concept of the pandas library. If one needed, the different references are available at the end of this section.

This tutorial was greatly inspired by [Aurélien Géron's Pandas notebook](https://github.com/ageron/handson-ml3/blob/main/tools_pandas.ipynb), all his interactive notebooks can also be found on [Google Colab](https://colab.research.google.com/github/ageron/handson-ml3/blob/main/index.ipynb). The [10 minutes to pandas tutorial](https://pandas.pydata.org/docs/user_guide/10min.html) is also a great place to start.

# Import the pandas library

To know more about packages, please see the relevant section in [02_python_numpy.ipynb](02_python_numpy.ipynb). To get started, we need to import NumPy and Pandas libraries:

In [1]:
import numpy as np
import pandas as pd

# Object creation

Creating a `Series` by passing a list of values, letting pandas create a default integer index:

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a `DataFrame` by passing a NumPy array, with datetime index and labeled columns:

In [3]:
pd.DataFrame(np.random.randn(6, 4), columns=["A", "B", "C", "D"])

          A         B         C         D
0  0.503049 -0.630086  1.152445 -0.594421
1 -1.024936 -0.059747  0.559940 -0.084136
2  0.179723  1.052082 -0.706382 -0.093009
3  0.923563  1.290148  1.407816  1.014811
4  0.449390 -0.625243  1.061649  0.481821
5 -0.213544 -0.756890  1.638186 -1.895201

Creating a `DataFrame` by passing a dictionary of objects that can be converted into a series-like structure:

In [4]:
df = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20230801"),
        "C": range(4),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    },
    index=["One", "Two", "Three", "Four"],
)
df

         A          B  C  D      E    F
One    1.0 2023-08-01  0  3   test  foo
Two    1.0 2023-08-01  1  3  train  foo
Three  1.0 2023-08-01  2  3   test  foo
Four   1.0 2023-08-01  3  3  train  foo

**Remark**: If you're using IPython, tab completion for column names (as well as public attributes) is automatically enabled. Just type `df.<TAB>` to see them.

# Data viewing

See the [Basics section](https://pandas.pydata.org/docs/user_guide/basics.html#basics). The columns of resulting `DataFrame` have different `dtypes`:

In [5]:
df.dtypes

A          float64
B    datetime64[s]
C            int64
D            int32
E         category
F           object
dtype: object

`info()` shows a quick statistic summary of your data:

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, One to Four
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      float64
 1   B       4 non-null      datetime64[s]
 2   C       4 non-null      int64
 3   D       4 non-null      int32
 4   E       4 non-null      category
 5   F       4 non-null      object
dtypes: category(1), datetime64[s](1), float64(1), int32(1), int64(1), object(1)
memory usage: 476.0+ bytes

`describe()` shows a quick statistic summary of your data:

In [7]:
df.describe()

         A                    B         C    D
count  4.0                    4  4.000000  4.0
mean   1.0  2023-08-01 00:00:00  1.500000  3.0
min    1.0  2023-08-01 00:00:00  0.000000  3.0
25%    1.0  2023-08-01 00:00:00  0.750000  3.0
50%    1.0  2023-08-01 00:00:00  1.500000  3.0
75%    1.0  2023-08-01 00:00:00  2.250000  3.0
max    1.0  2023-08-01 00:00:00  3.000000  3.0
std    0.0                  NaN  1.290994  0.0

Here is how to view the top and bottom rows of the frame:

In [8]:
df.head()

         A          B  C  D      E    F
One    1.0 2023-08-01  0  3   test  foo
Two    1.0 2023-08-01  1  3  train  foo
Three  1.0 2023-08-01  2  3   test  foo
Four   1.0 2023-08-01  3  3  train  foo

In [9]:
df.tail(3)

         A          B  C  D      E    F
Two    1.0 2023-08-01  1  3  train  foo
Three  1.0 2023-08-01  2  3   test  foo
Four   1.0 2023-08-01  3  3  train  foo

Display the index, columns:

In [10]:
print(df.index)
print(df.columns)

Index(['One', 'Two', 'Three', 'Four'], dtype='object')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

# Data selection

Pandas get optimized pandas data access methods, `.at`, `.iat`, `.loc` and `.iloc`. To go further, see the indexing documentation [Indexing and Selecting Data](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing) and [MultiIndex / Advanced Indexing](https://pandas.pydata.org/docs/user_guide/advanced.html#advanced).

## Selecting columns

Selecting a single column or a group of columns using `[]`:

In [11]:
df["A"]

One      1.0
Two      1.0
Three    1.0
Four     1.0
Name: A, dtype: float64

In [12]:
df[["A", "B"]]

         A          B
One    1.0 2023-08-01
Two    1.0 2023-08-01
Three  1.0 2023-08-01
Four   1.0 2023-08-01

## Selection by label using `.loc`  and `.at` methods

See more in [Selection by Label](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-label). For getting a row using its label:

In [13]:
df.loc["One"]

A                    1.0
B    2023-08-01 00:00:00
C                      0
D                      3
E                   test
F                    foo
Name: One, dtype: object

Selecting on a multi-axis by label:

In [14]:
df.loc[["One", "Two"], ["A", "B"]]

       A          B
One  1.0 2023-08-01
Two  1.0 2023-08-01

We can slice offer data using label, both endpoints are _included_:

In [15]:
df.loc["One":"Three", "A":"C"]

         A          B  C
One    1.0 2023-08-01  0
Two    1.0 2023-08-01  1
Three  1.0 2023-08-01  2

For getting fast access to a scalar (equivalent to the prior method):

In [16]:
df.at["Two", "B"]

Timestamp('2023-08-01 00:00:00')

## Selection by position using `.iloc`  and `.iat` methods

See more in [Selection by Position](https://pandas.pydata.org/docs/user_guide/indexing.html#indexing-integer). Selecting via the position of the passed integers:

In [17]:
df.iloc[3]

A                    1.0
B    2023-08-01 00:00:00
C                      3
D                      3
E                  train
F                    foo
Name: Four, dtype: object

By lists of integer position locations, similar to the NumPy/Python style:

In [18]:
df.iloc[[1, 2], [0, 2]]

         A  C
Two    1.0  1
Three  1.0  2

By integer slices, acting similar to NumPy/Python:

In [19]:
df.iloc[:3, 1:3]

               B  C
One   2023-08-01  0
Two   2023-08-01  1
Three 2023-08-01  2

For getting fast access to a scalar (equivalent to the prior method):

In [20]:
df.iat[1, 1]

Timestamp('2023-08-01 00:00:00')

## Conditional indexing

Selecting values from a DataFrame where a boolean condition is met:

In [21]:
df[df["C"] > 1]

         A          B  C  D      E    F
Three  1.0 2023-08-01  2  3   test  foo
Four   1.0 2023-08-01  3  3  train  foo

Using the `isin()` method for filtering:

In [22]:
df[df["C"].isin([0, 2])]

         A          B  C  D     E    F
One    1.0 2023-08-01  0  3  test  foo
Three  1.0 2023-08-01  2  3  test  foo

By integer slices, acting similar to NumPy/Python:

# Data setting

You can modify values of elements using `.at`, `.iat`, `.loc` and `.iloc` methode in the same way presented in chapter 2..

In [23]:
df.iloc[0, 0] = 25.0
df.loc[df["C"] > 1, "D"] = 100.0
df

          A          B  C    D      E    F
One    25.0 2023-08-01  0    3   test  foo
Two     1.0 2023-08-01  1    3  train  foo
Three   1.0 2023-08-01  2  100   test  foo
Four    1.0 2023-08-01  3  100  train  foo

You can modify an entire columns with the following:

- A unique value which will be assigned to the whole column
- A list to assigne different values through the columns. **size must be the same**
- A series which will only assigne values in matched index (nan values is assigned when a index from the dataframe is not included in the serie).

In [24]:
df["B"] = "Time"
df["F"] = [True, False, False, True]
df["A"] = pd.Series(range(4), index=["Three", "Four", "One", "five"])
df

         A     B  C    D      E      F
One    2.0  Time  0    3   test   True
Two    NaN  Time  1    3  train  False
Three  0.0  Time  2  100   test  False
Four   1.0  Time  3  100  train   True

If you assign a column which is not included to the dataFrame, it will be added

In [25]:
df["G"] = "Added"
df

         A     B  C    D      E      F      G
One    2.0  Time  0    3   test   True  Added
Two    NaN  Time  1    3  train  False  Added
Three  0.0  Time  2  100   test  False  Added
Four   1.0  Time  3  100  train   True  Added

## Set and reset index

In [26]:
df.reset_index()

   index    A     B  C    D      E      F      G
0    One  2.0  Time  0    3   test   True  Added
1    Two  NaN  Time  1    3  train  False  Added
2  Three  0.0  Time  2  100   test  False  Added
3   Four  1.0  Time  3  100  train   True  Added

In [27]:
df.reset_index(drop=True)

     A     B  C    D      E      F      G
0  2.0  Time  0    3   test   True  Added
1  NaN  Time  1    3  train  False  Added
2  0.0  Time  2  100   test  False  Added
3  1.0  Time  3  100  train   True  Added

In [28]:
df.set_index("A")

        B  C    D      E      F      G
A
2.0  Time  0    3   test   True  Added
NaN  Time  1    3  train  False  Added
0.0  Time  2  100   test  False  Added
1.0  Time  3  100  train   True  Added

# Data processing

## Missing data

Pandas primarily uses the value `NaN` to represent missing data. It is by default not included in computations. See the [Missing Data section](https://pandas.pydata.org/docs/user_guide/missing_data.html#missing-data). 
Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data:

In [29]:
df = pd.DataFrame(np.arange(10.0 * 6).reshape(10, 6))
df[(df % 17) == 0] = np.nan
df

      0     1     2     3     4     5
0   NaN   1.0   2.0   3.0   4.0   5.0
1   6.0   7.0   8.0   9.0  10.0  11.0
2  12.0  13.0  14.0  15.0  16.0   NaN
3  18.0  19.0  20.0  21.0  22.0  23.0
4  24.0  25.0  26.0  27.0  28.0  29.0
5  30.0  31.0  32.0  33.0   NaN  35.0
6  36.0  37.0  38.0  39.0  40.0  41.0
7  42.0  43.0  44.0  45.0  46.0  47.0
8  48.0  49.0  50.0   NaN  52.0  53.0
9  54.0  55.0  56.0  57.0  58.0  59.0

To drop any rows that have missing data:

In [30]:
df.dropna()

      0     1     2     3     4     5
1   6.0   7.0   8.0   9.0  10.0  11.0
3  18.0  19.0  20.0  21.0  22.0  23.0
4  24.0  25.0  26.0  27.0  28.0  29.0
6  36.0  37.0  38.0  39.0  40.0  41.0
7  42.0  43.0  44.0  45.0  46.0  47.0
9  54.0  55.0  56.0  57.0  58.0  59.0

To drop any column that have missing data:

In [31]:
df.dropna(axis=1)

      1     2
0   1.0   2.0
1   7.0   8.0
2  13.0  14.0
3  19.0  20.0
4  25.0  26.0
5  31.0  32.0
6  37.0  38.0
7  43.0  44.0
8  49.0  50.0
9  55.0  56.0

To drop any rows that have only missing data:

In [32]:
df.dropna(how="all")

      0     1     2     3     4     5
0   NaN   1.0   2.0   3.0   4.0   5.0
1   6.0   7.0   8.0   9.0  10.0  11.0
2  12.0  13.0  14.0  15.0  16.0   NaN
3  18.0  19.0  20.0  21.0  22.0  23.0
4  24.0  25.0  26.0  27.0  28.0  29.0
5  30.0  31.0  32.0  33.0   NaN  35.0
6  36.0  37.0  38.0  39.0  40.0  41.0
7  42.0  43.0  44.0  45.0  46.0  47.0
8  48.0  49.0  50.0   NaN  52.0  53.0
9  54.0  55.0  56.0  57.0  58.0  59.0

Filling missing data:

In [33]:
df.fillna(value=1000)

        0     1     2       3       4       5
0  1000.0   1.0   2.0     3.0     4.0     5.0
1     6.0   7.0   8.0     9.0    10.0    11.0
2    12.0  13.0  14.0    15.0    16.0  1000.0
3    18.0  19.0  20.0    21.0    22.0    23.0
4    24.0  25.0  26.0    27.0    28.0    29.0
5    30.0  31.0  32.0    33.0  1000.0    35.0
6    36.0  37.0  38.0    39.0    40.0    41.0
7    42.0  43.0  44.0    45.0    46.0    47.0
8    48.0  49.0  50.0  1000.0    52.0    53.0
9    54.0  55.0  56.0    57.0    58.0    59.0

In [34]:
df[0] = df[0].fillna(value=1000)
df

        0     1     2     3     4     5
0  1000.0   1.0   2.0   3.0   4.0   5.0
1     6.0   7.0   8.0   9.0  10.0  11.0
2    12.0  13.0  14.0  15.0  16.0   NaN
3    18.0  19.0  20.0  21.0  22.0  23.0
4    24.0  25.0  26.0  27.0  28.0  29.0
5    30.0  31.0  32.0  33.0   NaN  35.0
6    36.0  37.0  38.0  39.0  40.0  41.0
7    42.0  43.0  44.0  45.0  46.0  47.0
8    48.0  49.0  50.0   NaN  52.0  53.0
9    54.0  55.0  56.0  57.0  58.0  59.0

To get the boolean mask where values are `nan`:

In [35]:
pd.isna(df)

       0      1      2      3      4      5
0  False  False  False  False  False  False
1  False  False  False  False  False  False
2  False  False  False  False  False   True
3  False  False  False  False  False  False
4  False  False  False  False  False  False
5  False  False  False  False   True  False
6  False  False  False  False  False  False
7  False  False  False  False  False  False
8  False  False  False   True  False  False
9  False  False  False  False  False  False

## Duplicate data

In [36]:
df = pd.DataFrame(
    {
        "brand": ["Yum Yum", "Yum Yum", "Indomie", "Indomie", "Indomie"],
        "style": ["cup", "cup", "cup", "pack", "pack"],
        "rating": [4, 4, 3.5, 15, 5],
    }
)

df

     brand style  rating
0  Yum Yum   cup     4.0
1  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

You can find duplicate data using [`duplicated()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html). This method will detect every duplicated rows, by default the first occurrence is set on False and all others on True.

In [37]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

By setting `keep=last`, the last occurrence of each set of duplicated values is set on `False` and all others on `True`.

In [38]:
df.duplicated(keep="last")

0     True
1    False
2    False
3    False
4    False
dtype: bool

By setting `keep=False`, all duplicates are `True`.

In [39]:
df.duplicated(keep=False)

0     True
1     True
2    False
3    False
4    False
dtype: bool

To find duplicates on specific subset of column(s), use subset.

In [40]:
df.duplicated(subset=["brand"])

0    False
1     True
2    False
3     True
4     True
dtype: bool

We drop duplicates data we can use [`drop_duplicates()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.drop_duplicates.html?highlight=drop_duplicat#pandas.DataFrame.drop_duplicates). This method behaves in much the same way as `duplicated()`:

In [41]:
df.drop_duplicates()

     brand style  rating
0  Yum Yum   cup     4.0
2  Indomie   cup     3.5
3  Indomie  pack    15.0
4  Indomie  pack     5.0

## Concatenate dataframe

[`pd.concat()`](https://pandas.pydata.org/docs/reference/api/pandas.concat.html) allows to combine several dataframe together using their common column or index label. Unlike NumPy, pandas concatenation could be performed to unmatched size dataFrame, `NaN` values are added in order to keep built dataFrame integrity.

In [42]:
df1 = pd.DataFrame(np.arange(2 * 6).reshape(2, 6))
df1

   0  1  2  3   4   5
0  0  1  2  3   4   5
1  6  7  8  9  10  11

In [43]:
df2 = pd.DataFrame(2 * np.arange(4 * 4).reshape(4, 4))
df2

    0   1   2   3
0   0   2   4   6
1   8  10  12  14
2  16  18  20  22
3  24  26  28  30

Combine two dataframe using their common columns:

In [44]:
pd.concat([df1, df2])

    0   1   2   3     4     5
0   0   1   2   3   4.0   5.0
1   6   7   8   9  10.0  11.0
0   0   2   4   6   NaN   NaN
1   8  10  12  14   NaN   NaN
2  16  18  20  22   NaN   NaN
3  24  26  28  30   NaN   NaN

The two last columns of the resulting dataFrame contain `NaN` values. Resulting dataframe will keep source dataframe indexes. If you want to create a new index just set  `ignore_index=True`. Concatenate two dataframe using their common rows by setting axis = 1:

In [45]:
pd.concat([df1, df2], axis=1, ignore_index=True)

     0    1    2    3     4     5   6   7   8   9
0  0.0  1.0  2.0  3.0   4.0   5.0   0   2   4   6
1  6.0  7.0  8.0  9.0  10.0  11.0   8  10  12  14
2  NaN  NaN  NaN  NaN   NaN   NaN  16  18  20  22
3  NaN  NaN  NaN  NaN   NaN   NaN  24  26  28  30

Finally, if we want to only keep common row or column (depending of which axis is set), we can set `join="inner"`– as follows:

In [46]:
pd.concat([df1, df2], axis=1, join="inner")

   0  1  2  3   4   5  0   1   2   3
0  0  1  2  3   4   5  0   2   4   6
1  6  7  8  9  10  11  8  10  12  14

It is also possible to combine dataframe through the common values from one of their columns using [`merge()`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html]) method – as follows:

In [47]:
left = pd.DataFrame({"key": ["train", "test", "foo"], "lval": [1, 5, 2]})
right = pd.DataFrame({"key": ["foo", "train", "test"], "rval": [4, 5, 9]})
pd.merge(left, right, on="key")

     key  lval  rval
0  train     1     5
1   test     5     9
2    foo     2     4

**Remark**: pay attention, if both key merging columns have duplicate values, it will create duplicate rows.

In [48]:
left = pd.DataFrame({"key": ["foo"] * 3, "lval": [1, 5, 2]})
right = pd.DataFrame({"key": ["foo"] * 3, "rval": [4, 5, 9]})
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     1     9
3  foo     5     4
4  foo     5     5
5  foo     5     9
6  foo     2     4
7  foo     2     5
8  foo     2     9

# Statistics operators

Every statistics operators available on NumPy are also on Pandas. Operations in general _exclude_ missing data.

In [49]:
df = pd.DataFrame(np.array([[-2.5, 3.1, 7], [10, 11, np.nan]]))
df

      0     1    2
0  -2.5   3.1  7.0
1  10.0  11.0  NaN

In [50]:
for func in (df.min, df.max, df.sum, df.std, df.var):
    print(func.__name__, "columns=\n", func())
    print(func.__name__, "rows=\n", func(1))

min columns=
 0   -2.5
1    3.1
2    7.0
dtype: float64
min rows=
 0    -2.5
1    10.0
dtype: float64
max columns=
 0    10.0
1    11.0
2     7.0
dtype: float64
max rows=
 0     7.0
1    11.0
dtype: float64
sum columns=
 0     7.5
1    14.1
2     7.0
dtype: float64
sum rows=
 0     7.6
1    21.0
dtype: float64
std columns=
 0    8.838835
1    5.586144
2         NaN
dtype: float64
std rows=
 0    4.775284
1    0.707107
dtype: float64
var columns=
 0    78.125
1    31.205
2       NaN
dtype: float64
var rows=
 0    22.803333
1     0.500000
dtype: float64

# [`apply()` function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.apply.html)

Pandas DataFrame apply() function is used to efficiently apply a function along an axis of the DataFrame. It returns a new DataFrame object after applying the function to its elements. The for loop iterates through the numbers list and calls the `square()` function on each element. The `apply()` function is not defined for lists. It is a method of DataFrames and Series in Pandas.

The `apply()` function can be more efficient than a `for` loop in some cases, because it does not have to create a new list to store the results. However, the `for` loop is more readable and easier to understand:

In [51]:
def square(x):
    return x * x


numbers = [1, 2, 3, 4, 5]
df = pd.DataFrame({"number": [1, 2, 3, 4, 5]})

Using a `for` loop:

In [52]:
for number in numbers:
    print(square(number))

1
4
9
16
25

Using the `apply()` function:

In [53]:
squared_numbers = df["number"].apply(square)
print(squared_numbers)

0     1
1     4
2     9
3    16
4    25
Name: number, dtype: int64

The `apply()` function can be a powerful tool for applying functions to data structures in Python. It is important to choose the right tool for the application, and to understand the trade-offs between performance and readability. First we define the function we need to make it work:

In [54]:
def square(x):
    return x * x


def add_one(x):
    return x + 1


def uppercase(letter):
    return letter.upper()

Then we create a DataFrame to compare the different methods and apply the functions:

In [55]:
df = pd.DataFrame({"number": [1, 2, 3, 4, 5], "letter": ["a", "a", "b", "b", "c"]})

df["square"] = df["number"].apply(square)
df["add_one"] = df["number"].apply(add_one)
df["uppercase"] = df["letter"].map(uppercase)

df

   number letter  square  add_one uppercase
0       1      a       1        2         A
1       2      a       4        3         A
2       3      b       9        4         B
3       4      b      16        5         B
4       5      c      25        6         C

## `lambda` function

A `lambda` function is a small, anonymous function that can be used as an argument to other functions. Lambda functions are often used in Python to perform simple tasks that would otherwise require a more complex function. The `arguments` are the input values to the function, and the `expression` is the code that is executed when the function is called.

In [56]:
df["modulo"] = df["number"].apply(lambda x: x % 3)
letter_mapping = {"a": "anaconda", "b": "boa", "c": "cobra"}
df["snake"] = df["letter"].apply(lambda x: letter_mapping[x])
df

   number letter  square  add_one uppercase  modulo     snake
0       1      a       1        2         A       1  anaconda
1       2      a       4        3         A       2  anaconda
2       3      b       9        4         B       0       boa
3       4      b      16        5         B       1       boa
4       5      c      25        6         C       2     cobra

# References for Pandas

If you want to get more insights and learn more about Matplotlib, please visit the following two very good references:

- [10 minutes to pandas](https://pandas.pydata.org/docs/user_guide/10min.html)
- [Comparison with spreadsheets](https://pandas.pydata.org/docs/getting_started/comparison/comparison_with_spreadsheets.html)
- [Pandas cheatsheet](https://github.com/pandas-dev/pandas/blob/main/doc/cheatsheet/Pandas_Cheat_Sheet.pdf)

# Test with a timeseries csv

Import the plot library

In [57]:
import plotly.express as px

Import data from csv

In [ ]:
df_smartmeter

## Date time
Using to_datetime, convert object to datetime

In [ ]:
df_smartmeter["timestamp_utc"]

## Self-consumption
Calcul the self consumption from consumption and production with apply a function (lambda)

In [ ]:
df_smartmeter["sc"]

In [61]:
df_smartmeter["sc"].sum() / df_smartmeter["kWh_to_grid"].sum() * 100

np.float64(1.3290674216336846)

## Plot SC
Using plotly express, plot the self-consumption

## Add a constant production
Add a constant production between 1st january to en of december of 2024.

Using date_range to create a DatetimeIndex

Add a 50 W constant consumption to the dataframe

In [ ]:
hydro_production_df

Merge with the timeseries smartmeter data

In [ ]:
df_smartmeter

Recalculate the SC with the constant production

In [66]:
df_smartmeter["sc_hydro"].sum() / df_smartmeter["production_kWh"].sum() * 100

np.float64(52.70502283105024)

Plot this SC